export const PUSH_PRODUCT_TO_CART = 'PUSH_PRODUCT_TO_CART';
export const REMOVE_ITEM_CART_BY_ID = 'REMOVE_ITEM_CART_BY_ID';
export const SUBSTRACT_CART_BY_ID = 'SUBSTRACT_CART_BY_ID';
export const ADD_PRODUCT = 'ADD_PRODUCT';
